server:
  port: 10000

eureka:
  instance:
    hostname: "localhost"
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: "http://localhost:10000/eureka/"
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka-server